# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/307acdf3-6dc1-4203-ac37-d092c1208690";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/65f65914-1bd6-4dbc-a990-f43e2a684372"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
