console_title_template = '[{{ if .Root }}root @ {{ end }}{{ .Shell }} -- in -> {{ .Folder }}]'
version = 3
final_space = true

[secondary_prompt]
  template = '╰─ '
  foreground = '#6feb8e'
  background = 'transparent'

[transient_prompt]
  template = ' '
  foreground = '#6feb8e'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' /\_____/\ '
    foreground = '#6feb8e'
    type = 'text'
    style = 'plain'

    [blocks.segments.options]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  newline = true

  [[blocks.segments]]
    template = '{{ if gt .Code 0 }}(-[<#e06c75>0</>].[<#e06c75>0</>]-){{ else }}(-[<#6feb8e> </>].[<#6feb8e> </>]-){{ end }}'
    foreground = '#6feb8e'
    type = 'text'
    style = 'plain'

    [blocks.segments.options]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ if .WSL }} on {{ end }}{{ .Icon }} '
    foreground = '#6feb8e'
    background = '#151b1b'
    type = 'os'
    style = 'diamond'

    [blocks.segments.options]
      alpine = ''
      arch = ''
      centos = ''
      debian = ''
      elementary = ''
      fedora = ''
      gentoo = ''
      linux = ''
      macos = ''
      manjaro = ''
      mint = ''
      opensuse = ''
      raspbian = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    leading_diamond = ''
    template = ' <#6feb8e></> {{ .UserName }} <#6feb8e>::</> <#6feb8e></> {{ .HostName }} '
    foreground = '#7eb8da'
    background = '#2B2D42'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = '  {{ .Name }} '
    foreground = '#011627'
    powerline_symbol = ''
    background = '#6feb8e'
    type = 'shell'
    style = 'powerline'

  [[blocks.segments]]
    template = '  admin '
    foreground = '#011627'
    powerline_symbol = ''
    background = '#6feb8e'
    type = 'root'
    style = 'powerline'

  [[blocks.segments]]
    template = '   cmake {{ .Full }} '
    foreground = '#011627'
    powerline_symbol = ''
    background = '#6feb8e'
    type = 'cmake'
    style = 'powerline'

  [[blocks.segments]]
    template = '  {{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }} '
    foreground = '#011627'
    powerline_symbol = ''
    background = '#6feb8e'
    type = 'python'
    style = 'powerline'

    [blocks.segments.options]
      display_mode = 'context'

  [[blocks.segments]]
    template = ' ‭ {{ .Full }} '
    foreground = '#011627'
    powerline_symbol = ''
    background = '#6feb8e'
    type = 'go'
    style = 'powerline'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#011627'
    powerline_symbol = ''
    background = '#6feb8e'
    type = 'rust'
    style = 'powerline'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#6feb8e'
    powerline_symbol = ''
    background = '#151b1b'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#4a4a4a{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#4a4a4a{{ end }}', '{{ if gt .Ahead 0 }}#5a5a5a{{ end }}', '{{ if gt .Behind 0 }}#5a5a5a{{ end }}']

    [blocks.segments.options]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '--[{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}]--'
    foreground = '#6feb8e'
    type = 'battery'
    style = 'plain'
    foreground_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#ff5722{{end}}', '{{if eq "Full" .State.String}}#4caf50{{end}}']

    [blocks.segments.options]
      charged_icon = '<#ffffff></> '
      charging_icon = ' '
      discharging_icon = '<#ffff00></> '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╭─'
    foreground = '#D6DEEB'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .CurrentDate | date .Format }}'
    foreground = '#6feb8e'
    type = 'time'
    style = 'plain'

    [blocks.segments.options]
      time_format = '<#D6DEEB>[  15:04:05 ]</> <#6feb8e>[ </>  2 Jan, Monday <#6feb8e>]</> '

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' '
    foreground = '#3a3a3a'
    background = '#6abfc6'
    type = 'text'
    style = 'diamond'

    [blocks.segments.options]
      always_enabled = true

  [[blocks.segments]]
    trailing_diamond = ''
    template = 'RAM: {{ (div ((sub .PhysicalTotalMemory .PhysicalAvailableMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB'
    foreground = '#B6D6F2'
    background = '#1b1e34'
    type = 'sysinfo'
    style = 'diamond'

    [blocks.segments.options]
      style = 'roundrock'
      threshold = 0.0

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    foreground = '#6feb8e'
    background = '#3a3a3a'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}#E44141{{ end }}']
    foreground_templates = ['{{ if gt .Code 0 }}#D6DEEB{{ end }}']

    [blocks.segments.options]
      always_enabled = true

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ .FormattedMs }} '
    foreground = '#B6D6F2'
    background = '#575656'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.options]
      style = 'roundrock'
      threshold = 0.0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '├─'
    foreground = '#D6DEEB'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    leading_diamond = '[<#6feb8e>  </><#B6D6F2> in </>'
    template = ' {{ .Path }} <#D6DEEB>]</>'
    foreground = '#B6D6F2'
    type = 'path'
    style = 'diamond'

    [blocks.segments.options]
      folder_icon = '  '
      folder_separator_icon = '  '
      home_icon = ' '
      max_depth = 3.0
      style = 'agnoster_short'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─'
    foreground = '#D6DEEB'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = '❯ '
    foreground = '#6feb8e'
    type = 'status'
    style = 'plain'

    [blocks.segments.options]
      always_enabled = true
